### ISSUE TITLE
Version 1.3 unstable?

### ISSUE THREAD

**Issue by flagsvg** [jamesy012/OpenPlanet-BestCheckpoints#12]
Since the latest update the plugin always crashes for me as soon as i leave a map, with this message:

"Plugin has become unstable, so it has been stopped" and the log saying "Unrolling dangling script UI stack: Main.as line 912".

**Comment by jamesy012** [comment]
ahhh shit.. thats not good, I'll try to find out whats going on in the next few days

**Comment by jamesy012** [comment]
Thanks for letting me know i'll make an update on openplanet for it soon
