### ISSUE TITLE
+0 speed issue 

### ISSUE THREAD

**Issue by CatzHoekk** [jamesy012/OpenPlanet-BestCheckpoints#18]
That happens quite a lot. I have not really figured out how this comes about. 

![image](https://user-images.githubusercontent.com/69237200/167278091-0c02da51-0a2b-4b48-972e-f918dfd581a9.png)

**Comment by jamesy012** [comment]
if you have played the map before it acts a little weird since it only updates the values when you score a new pb

does that sound like it would be the cause? 

or it's just not working even after a new personal best?

could you check if the best speed delta is working?
curious if maybe it's just not getting the speeds

**Comment by CatzHoekk** [comment]
Hmm, can´t really tell from memory, will need to observe that the next time it happens. It´s possible that at this point in time i didn´t have a pb since the last mapchange. 

But it should still have some proper values to compare it to, from whenever i drove the pb before, no?

**Comment by jamesy012** [comment]
only ways I can think of this happening would be it setting both values to the speed or it's just not getting the speed meaning the delta would always be 0

yeah keep me updated

**Comment by CatzHoekk** [comment]
It seems it doesn´t remember the overall pb speeds if you didn´t drive the pb in the current session.

![image](https://user-images.githubusercontent.com/69237200/167380846-143b3c8f-c11b-40f6-8c56-f2bb02a922a2.png)

I looked at a handful of json files after i closed the game and "pbSpeed" is 0 everywhere. (On some maps "speed" is 0 aswell but not sure if that´s even indented to be saved. )

**Comment by jamesy012** [comment]
alright cool, very odd

something's up with the cars Displayed speed, or atleast the plugins way of accessing it
seems like it did work at some point since Best speeds has some data...

I'll work out a replacement for it tomorrow and make an update during the week

**Comment by CatzHoekk** [comment]
i use the splitspeeds plugin too and it shows proper values, if that helps. Like, it´s almost the same functionality. So maybe that´s a route.

**Comment by CatzHoekk** [comment]
I haven´t seen the issue in a while, i believe your fix is reliable. I´ll close it.
