### ISSUE TITLE
Feature Request: show PB

### ISSUE THREAD

**Issue by cat64k** [jamesy012/OpenPlanet-BestCheckpoints#3]
show PB time recorded by this tool

I wanna know which time the pb time is recorded on this tool, since the PB might be different from the official PB at the track

(for example if you have older PB's before data reset, you drove you PB on a different PC, you drove your PB within a WarmUp or you disabled this plugin for a short amount of time)

**Comment by jamesy012** [comment]
Makes sense I'll add that to the ui next time I work on the plugin

**Comment by jamesy012** [comment]
![Screenshot 2022-02-26 211141](https://user-images.githubusercontent.com/2156228/155839224-cb0d53d6-4152-452d-b9ae-488a70bf493b.png)
added it to the top bar section
will be in the next update
