### ISSUE TITLE
Seems to bug when you hide the interface

### ISSUE THREAD

**Issue by astr0n0mia** [jamesy012/OpenPlanet-BestCheckpoints#6]
Hi !

When I hide the ui during the run, then enable it, all the cps seems to be wrong and the theorical time is impossible.
And the option for hiding the UI of the plugin, hide it when you have the interface of TM enable, then enable it when you disable the interface of TM.

I hope my english is not too bad, sorry if I did some mistakes.

Otherwise the plugin is really good, and seems to work well, as long as you keep the interface of TM enable.

**Comment by jamesy012** [comment]
Odd someone mentioned this to me on discord also
thanks for making it an issue here
will look into whats happening soon

**Comment by jamesy012** [comment]
Turns out the value I was using to see how long the current race had been running for just didn't update when the interface was off
should be fixed for next update 🤞

**Comment by astr0n0mia** [comment]
Nice !
