### ISSUE TITLE
Add an option to show the PB column as delta to your best.

### ISSUE THREAD

**Issue by CatzHoekk** [jamesy012/OpenPlanet-BestCheckpoints#7]
![Trackmania_hxJBWqK4p7](https://user-images.githubusercontent.com/69237200/155754198-6d629325-f7b1-4605-a6ef-e93a0d08cee4.png)

Would be cool if the marked column could be displayed so it just shows the delta to your best. Imo that would make it much easier to see which cps are still very bad.

**Comment by jamesy012** [comment]
Was trying out having it update during a run but I found the numbers it was showing to be too confusing.
will be in the next update
![Screenshot 2022-02-26 190812](https://user-images.githubusercontent.com/2156228/155835585-31aa866a-af05-471b-80f9-31d22dd47f30.png)

**Comment by CatzHoekk** [comment]
Cool, thank you.
